import type { Metadata } from "next";
import "./globals.css";
import { woff } from "@/fonts";

export const metadata: Metadata = {
  title: "React Fancy Button Challenge",
  description: "Generated by create next app",
  icons: "icon2.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={woff.className}>{children}</body>
    </html>
  );
}
